export const REPORT_COLUMNS = [
  { id: 'rank', label: 'Rank' },
  { id: 'field', label: 'Field' },
  { id: 'group', label: 'Group' },
  { id: 'crop', label: 'Crop' },
  { id: 'variety', label: 'Variety' },
  { id: 'season', label: 'Season' },
  { id: 'location', label: 'Location' },
  { id: 'coordinates', label: 'Coordinates' },
  { id: 'areaHa', label: 'Area (ha)' },
  { id: 'sowingDate', label: 'Sowing' },
  { id: 'plantingDate', label: 'Planting' },
  { id: 'latestIndexValue', label: 'Index value' },
  { id: 'indexDelta', label: 'Change' },
  { id: 'cloudFreeRecencyDays', label: 'Recency' },
  { id: 'weatherRiskLabel', label: 'Weather risk' },
  { id: 'actualYield', label: 'Actual yield' },
  { id: 'latestImageDate', label: 'Image date' },
  { id: 'score', label: 'Score' },
  { id: 'preview', label: 'Preview' },
] as const;

export const DEFAULT_REPORT_COLUMNS = [
  'rank',
  'field',
  'group',
  'crop',
  'variety',
  'location',
  'areaHa',
  'sowingDate',
  'latestIndexValue',
  'indexDelta',
  'cloudFreeRecencyDays',
  'weatherRiskLabel',
  'actualYield',
  'latestImageDate',
  'score',
  'preview',
];
